
###
put http://172.18.231.1:5000/var/
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
     "nombre":"variable3",
      "norm":"vv",
      "codigo":"codigo",
      "desechado":1,
      "descripcion":"descr",
      "base":"63448a36a88b5ff8c83e3fb8"
}


###
DELETE http://172.18.231.1:5000/var/
Authorization: DTSI IS GAH
Content-Type: application/json
usuario: rlavagnino

{
    "variable":"633f344e6d2865e79849c38b"
}

###
Patch http://172.18.231.1:5000/var/
Authorization: DTSI IS GAH
Content-Type: application/json
usuario: rlavagnino

{
    "desechado":1
    ,"nombre":"miau3"
    ,"variable":"633f345d6d2865e79849c38e"
}


###
post http://172.18.231.1:5000/var/data/base
Authorization: DTSI IS GAH
Content-Type: application/json
usuario: rlavagnino

{

    "base":"63448a36a88b5ff8c83e3fb8"
}

###
post http://172.18.231.1:5000/var/data/
Authorization: DTSI IS GAH
Content-Type: application/json
usuario: rlavagnino

{

}