###
get http://172.18.231.1:5000/base/rlavagnino

{

}

###
get http://172.18.231.1:5000/base/id/rlavagnino/633dbf075c4ee5bdaad08c1f

{

}

###
put http://172.18.231.1:5000/base/
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
    "usuario": "rlavagnino"
    ,"tipo":"EXCEL"
    ,"dueño":"Roberto"
    ,"departamento":"dtsi"
    ,"nombre":"mtg 1"
}


###
DELETE http://172.18.231.1:5000/base/633ee364ca381be4d485d81e
Authorization: DTSI IS GAH 
Content-Type: application/json

{
    "usuario": "rlavagnino"
}


###
PATCH http://172.18.231.1:5000/base
Authorization: DTSI IS GAH 
Content-Type: application/json

{
 "usuario":"rlavagnino"
 ,"id":"633ee364ca381be4d485d81e"
 ,"dueño": "hola2"
 ,"tipo":"json"
}



###
put http://172.18.231.1:5000/base/est/preprocesar
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
   "base":"63448a36a88b5ff8c83e3fb8"
}

###
put http://172.18.231.1:5000/base/est/trabajar
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
   "base":"63448a36a88b5ff8c83e3fb8"
}

###
put http://172.18.231.1:5000/base/est/modelar
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
   "base":"63448a36a88b5ff8c83e3fb8"
}


###
put http://172.18.231.1:5000/base/est/dormir
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
   "base":"63448a36a88b5ff8c83e3fb8"
}


###
put http://172.18.231.1:5000/base/est/cerrar
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
   "base":"63448a36a88b5ff8c83e3fb8"
}


###
put http://172.18.231.1:5000/base/version
Authorization: DTSI IS GAH 
Content-Type: application/json
usuario: rlavagnino

{
   "base":"63448a36a88b5ff8c83e3fb8"
   ,"archivo":"yo.xlsx"
   ,"registros":"250000"
   ,"dueño":"rlavagnino"
}







