###
get http://172.18.231.1:5000/base/rlavagnino

{

}

###
get http://172.18.231.1:5000/base/id/rlavagnino/633dbf075c4ee5bdaad08c1f

{

}

###
put http://172.18.231.1:5000/base/
Authorization: DTSI IS GAH 
Content-Type: application/json

{
    "usuario": "rlavagnino"
    ,"tipo":"EXCEL"
    ,"dueño":"Roberto"
    ,"departamento":"dtsi"
    ,"nombre":"mtg 3"
}


###
DELETE http://172.18.231.1:5000/base/633dbf5ef53e7b0e93753fd7
Authorization: DTSI IS GAH 
Content-Type: application/json

{
    "usuario": "rlavagnino"
}


###
PATCH http://172.18.231.1:5000/base
Authorization: DTSI IS GAH 
Content-Type: application/json

{
 "usuario":"rlavagnino"
 ,"id":"633dbf075c4ee5bdaad08c1f"
 ,"dueño": "hola2"
 ,"tipo":"json"
}