###

get http://172.18.231.1:5000/auth/rlavagnino

{

}  


###
put http://localhost:5000/auth
Content-Type: application/json
Authorization: DTSI IS GAH

{
    "usuario":"rlavagnino"
    ,"nuevo_usuario":"rolavagnino"
    ,"nuevo_nombre": "Roberto Guillermo"
    ,"nuevo_apellido":"Lavagnino Rodriguez"
}  


###
DELETE http://localhost:5000/auth
Content-Type: application/json
Authorization: DTSI IS GAH

{
    "usuario":"rlavagnino"
    ,"usuario_eliminar":"rolavagnino"
}  